name: Test Python

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd ingrid
        pip install -r requirements-dev.txt

    - name: Test with pytest
      run: |
        coverage run -m pytest -c ingrid/setup.cfg
        coveralls

    - name: List directory
      run: |
        ls -la

    - name: Archive test results
      uses: actions/upload-artifact@v1
      with:
        name: test-report ${{ matrix.node-version }}
        path: junit.xml

    - name: Archive test coverage report
      uses: actions/upload-artifact@v1
      with:
        name: test-coverage ${{ matrix.node-version }}
        path: coverage.xml

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.github_token }}
        # flag-name: run-${{ matrix.test_number }}
        # path-to-lcov: .coverage/
        parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.1
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
